<?php

// Include the main TCPDF library (search for installation path).
require_once('../../TCPDF-main/tcpdf.php');

// extend TCPF with custom functions
class MYPDF extends TCPDF {

    // Load table data from file
    public function LoadData() {
        // Read file lines
        include("../../db.php");
        $select = "SELECT * FROM room ";

        $query = mysqli_query($con,$select);
        return $query;
    }

    // Colored table
    public function ColoredTable($header,$data) {
        // Colors, line width and bold font
        $this->SetFillColor(192, 192, 192); // Light Gray for fill
        $this->SetTextColor(0, 0, 0); // Black text for high contrast
        $this->SetDrawColor(105, 105, 105); // Dim Gray for draw color
        $this->SetLineWidth(0.3);
        $this->SetFont('', 'B');

        // Colors, line width and bold font
          //  $this->SetFillColor(100, 149, 237); // Cornflower Blue for fill
            //$this->SetTextColor(255, 255, 255); // White text
           // $this->SetDrawColor(65, 105, 225); // Royal Blue for draw color
           //$this->SetLineWidth(0.3);
           // $this->SetFont('', 'B');
        // Header
        $w = array(30, 40, 40, 30, 50, 50);
        $num_headers = count($header);
        for($i = 0; $i < $num_headers; ++$i) {
            $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', 1);
        }
        $this->Ln();
        // Color and font restoration
        $this->SetFillColor(224, 235, 255);
        $this->SetTextColor(0);
        $this->SetFont('');
        // Data
        $fill = 0;
        foreach($data as $row) {

            $this->Cell($w[0], 6,$row["room_id"], 'LR', 0, 'C', $fill);
            $this->Cell($w[1], 6, $row["room"], 'LR', 0, 'C', $fill);
            $this->Cell($w[2], 6,number_format ($row["floor"]), 'LR', 0, 'C', $fill);
            $this->Cell($w[3], 6, number_format($row["capacity"]), 'LR', 0, 'C', $fill);
            $this->Cell($w[4], 6, number_format($row["current_occupancy"]), 'LR', 0, 'C', $fill);
            $this->Cell($w[5], 6, $row["status"], 'LR', 0, 'C', $fill);
            
            $this->Ln();
            $fill=!$fill;
        }
        $this->Cell(array_sum($w), 0, '', 'T');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('SAS');
$pdf->SetTitle('Room Details');
$pdf->SetSubject('ROOM DETAILS');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Room Details', 'Generated by Siswi Accommodation System');

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', '', 12);

// add a page
$pdf->AddPage();

// column titles
$header = array('Room ID', 'Room', 'Floor', 'Capacity','Current Occupancy','Status');

// data loading
$data = $pdf->LoadData();

// print colored table
$pdf->ColoredTable($header, $data);

// ---------------------------------------------------------

// close and output PDF document
$pdf->Output('room_print.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+